version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [appnet]

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: >
      gunicorn gestionnaire_mdp.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 60
    ports:
      - "127.0.0.1:8000:8000"
    networks: [appnet]

  frontend:
    build: ./frontend
    depends_on: [backend]
    environment:
      VITE_API_BASE: https://api.mon-site.ca
    command: ["npm","run","preview","--","--host","0.0.0.0","--port","4173"]
    ports:
      - "127.0.0.1:4173:4173"
    networks: [appnet]

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
