# tout en haut (remplace l’existant)
name: mdp_prod

services:
  db:
    networks: [appnet]               # interne uniquement

  backend:
    networks: [appnet, edge]         # interne + traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=edge
      - traefik.http.routers.mdp_api.rule=Host(`mdp-api.mon-site.ca`)
      - traefik.http.routers.mdp_api.entrypoints=web
      - traefik.http.services.mdp_api.loadbalancer.server.port=8000

  frontend:
    networks: [edge]                 # servi par traefik seulement
    labels:
      - traefik.enable=true
      - traefik.docker.network=edge
      - traefik.http.routers.mdp_front.rule=Host(`mdp.mon-site.ca`)
      - traefik.http.routers.mdp_front.entrypoints=web
      - traefik.http.services.mdp_front.loadbalancer.server.port=80

networks:
  appnet: {}
  edge:
    external: true                   # IMPORTANT: utilise le réseau /srv/edge
